---
name: Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master
  # branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  test-linux:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Install Required Packages
        run: sudo apt-get install -qq libxml-xpath-perl xsltproc shellcheck

      - name: Print Tool Versions
        run: |
          java -version
          mvn --version
          bash --version
          xsltproc --version
          yq --version

      - name: Cleanup Maven Profiles
        run: |
          if [ -e "$HOME/.m2/settings.xml" ]; then
            sed  -i '/<profiles>/,/<\/profiles>/d' "$HOME/.m2/settings.xml"
            cat $HOME/.m2/settings.xml
          fi
          mvn -B help:all-profiles

      - name: Run tests and shellcheck
        run: make tests check


  test-windows:

    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Choco install yq
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install yq shellcheck

      - name: Print Tool Versions
        shell: bash
        run: |
          java -version
          mvn --version
          bash --version
          xsltproc --version
          yq --version

      - name: Cleanup Maven Profiles
        shell: bash
        run: |
          if [ -e "$HOME/.m2/settings.xml" ]; then
            sed  -i '/<profiles>/,/<\/profiles>/d' "$HOME/.m2/settings.xml"
            cat $HOME/.m2/settings.xml
          fi
          mvn -B help:all-profiles

      - name: Run Tests
        shell: bash
        run: |
          tests/test_comp.sh

